package go_microsoftapis

const protoHTTPS = "https://"
const constSubDomainTranslateGlobal = "api"
const constSubDomainTranslateNorthAmerica = "api-nam"
const constSubDomainTranslateEurope = "api-eur"
const constSubDomainTranslateAsiaPacific = "api-apc"
const urlTranslate = ".cognitive.microsofttranslator.com/"
const endPointTranslateTranslate = "translate"
const endPointTranslateSpeak = "speak"
const endPointTranslateDictionaryLookup = "dictionary/lookup"
const endPointTranslateDictionaryExamples = "dictionary/examples"
const endPointTranslateTransliterate = "transliterate"
const endPointTranslateLanguages = "languages"
const endPointTranslateDetect = "detect"
const appNameTranslate = "MSTranslatorAndroidApp"
const appSecretTranslate = "oik6PdDdMnOXemTbwvMn9de/h9lFnfBaCWbGMMZqqoSaQaqUOqjVGm5NqsmjcBI1x+sS9ugjB55HEJWRiFXYFw=="
